### ISSUE TITLE
Cookies.noConflict() not working

### ISSUE THREAD

**Issue by wwestonh** [js-cookie/js-cookie#580]
Starting late last night (12/11/2019) I noticed that the method noConflict() was no longer recognized using the CDN call:

<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.mjs"></script>

Error:

"Uncaught TypeError: Cookies.noConflict is not a function"

**Comment by carhartl** [comment]
If you're including the module version this doesn't make sense. If you need `noConflict()`, don't use the module:

```
<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
```

**Comment by carhartl** [comment]
Probably caused by https://github.com/js-cookie/js-cookie/commit/47b538d69f8fd36e821015ab4ce8dec6e0a122e6

**Comment by carhartl** [comment]
Bumped the beta and pushed a new version to npm.

**Comment by wwestonh** [comment]
Will the jsdelivr CDN version at https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js be updated?

**Comment by carhartl** [comment]
I don’t know. I think so, it’ll pick up whatever the tag “beta” is pointing to on npm.
